name: progetto_finale
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  path_provider: ^2.1.2
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_riverpod: ^2.4.9
  # http: ^1.1.0 # Da decommentare quando collegherai il server